dist: xenial

language: cpp
compiler: gcc
os:
- linux

language: python
python:
  - "3.7"


# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install astropy

# command to run tests
script:
#  install in develop mode, otherwise imports will not work
  - pip install -e .
  - python -c "import pyimfit"
  - cd pyimfit/tests ; pytest
