dist: xenial

language: cpp
compiler: gcc
os:
- linux

language: python
python:
  - "3.7"


# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python setup.py install
  - python -c "import pyimfit"
