
language: cpp
compiler: gcc

language: python

matrix:
  include:
    - os: linux
      - dist: xenial
      - python: 3.7


# command to install dependencies
install:
  - pip install -r requirements.txt
  # install astropy so we can run tests
  - pip install astropy

# command to run tests
script:
  #  Travis CI peculiarity: install in develop mode, otherwise imports will not work!
  - pip install -e .
  - python -c "import pyimfit"
  # note that the tests require astropy be installed
  - cd pyimfit/tests ; pytest
